
GenerateGmcsDatabase <- function(gmcs.list.txt = NULL, # each element of the list is are strings with the gMCSs, separated by "--". each element of the list for each task
                                     gmcs.list.tab = NULL, # each element of the list contains a table of gMCSS loaded from text. each element of the list for each task
                                     gmcs.list.mat = NULL, # each element of the list contains a binary matrix of gMCSs by genes. each element of the list for each task
                                     table.genes.HumanGEM = NULL){
  
  # variable names are generated by assuming they work with ENSEMBL 
  
  if ((is.null(gmcs.list.txt) + is.null(gmcs.list.tab) + is.null(gmcs.list.mat)) == 3){
    stop("there is no information given to the function")
  } else if ((!is.null(gmcs.list.txt) + !is.null(gmcs.list.tab) + !is.null(gmcs.list.mat)) >1){
    stop("Only one source of information must be givven to the function")
  }
  
 
  # transform any source of information into the text format
  
  # gmcs.list.txt <- gMCSs.ENSEMBL.txt; gmcs.list.tab <- NULL; gmcs.list.mat <- NULL
  # gmcs.list.txt <- NULL; gmcs.list.tab <- gMCSs.ENSEMBL.all[1:57]; gmcs.list.mat <- NULL
  # gmcs.list.txt <- NULL; gmcs.list.tab <- NULL; gmcs.list.mat <- gMCSs.ENSEMBL.mat
  
  if (!is.null(gmcs.list.txt)){
    # gMCSs.ENSEMBL.raw <- gmcs.list.txt
    if (!is.list(gmcs.list.txt)) {gmcs.list.txt <- list(gmcs.list.txt)}
    for (n in 1:length(gmcs.list.txt)){
      if (length(gmcs.list.txt[[n]])>0){
        # order and sort
        gmcs.list.txt[[n]] <- sapply(lapply(strsplit(gmcs.list.txt[[n]],'--'),sort), paste, collapse = "--")
      } else {gmcs.list.txt[[n]] <- NULL}
    }
  } else if (!is.null(gmcs.list.tab)){
    # gMCSs.ENSEMBL.raw <- gmcs.list.tab
    if (!is.list(gmcs.list.tab)) {gmcs.list.tab <- list(gmcs.list.tab)}
    gmcs.list.txt <- list()
    for (n in 1:length(gmcs.list.tab)){
      if (prod(dim(gmcs.list.tab[[n]]))>0){
        # order and sort
        gmcs.list.txt[[n]] <- apply(gmcs.list.tab[[n]],1,function(x){paste(sort(x[x!=""]), collapse = "--")})
      } else {gmcs.list.txt[[n]] <- NULL}
    }
    
  } else if (!is.null(gmcs.list.mat)){
    # gMCSs.ENSEMBL.raw <- gmcs.list.mat
    if (!is.list(gmcs.list.mat)) {gmcs.list.mat <- list(gmcs.list.mat)}
    gmcs.list.txt <- list()
    for (n in 1:length(gmcs.list.mat)){
      if (prod(dim(gmcs.list.mat[[n]]))>0){
        # order and sort
        gmcs.list.txt[[n]] <- apply(gmcs.list.mat[[n]],1,function(x){as.numeric(which(x>0))})
        gmcs.list.txt[[n]] <- lapply(gmcs.list.txt[[n]], function(x){colnames(gmcs.list.mat[[n]])[x]})
        gmcs.list.txt[[n]] <- sapply(gmcs.list.txt[[n]],function(x){paste(sort(x), collapse = "--")})
      } else {gmcs.list.txt[[n]] <- NULL}
    }
  }
  
  # name the list of gMCSs
  for (n in 1:length(gmcs.list.txt)){
    if (length(gmcs.list.txt[[n]])>0) { 
      names(gmcs.list.txt[[n]]) <- paste0(n, '--', 1:length(gmcs.list.txt[[n]]))
    }
  }
  
  gMCSs.ENSEMBL.raw <- gmcs.list.txt
  gmcs.list.txt <- do.call(c, gmcs.list.txt)
  
  # generate table to relate all gMCSs
  table.gMCSs <- do.call(rbind, strsplit(names(gmcs.list.txt), '--'))
  table.gMCSs <- data.frame(task = as.character(table.gMCSs[,1]), 
                            gMCS = as.character(table.gMCSs[,2]),
                            idx = NA)
  
  # generate simplified list
  gmcs.list.txt.unique <- unique(gmcs.list.txt)
  gmcs.list.txt.unique <- gmcs.list.txt.unique[order(nchar(gmcs.list.txt.unique), decreasing = F)]
  
  # store information of the original position
  table.gMCSs$idx <- match(gmcs.list.txt, gmcs.list.txt.unique)
  
  # total list of genes
  genes.gMCSs.ENSEMBL <- sort(unique(unlist(strsplit(gmcs.list.txt.unique, '--'))))
  

  # add auxiliary information
  gMCSs.ENSEMBL.txt <- gmcs.list.txt.unique
  gMCSs.ENSEMBL.txt.list <- lapply(strsplit(gMCSs.ENSEMBL.txt, '--'),sort) # array of unique gMCSs along task, but separated
  gMCSs.ENSEMBL.txt.list.num <- lapply(gMCSs.ENSEMBL.txt.list, match, genes.gMCSs.ENSEMBL) # array of unique gMCSs along task, but separated

  
  # generate binary total matrix of gMCS x genes
  gMCSs.ENSEMBL.mat <- matrix(0,nrow = length(gmcs.list.txt.unique), ncol = length(genes.gMCSs.ENSEMBL))
  rownames(gMCSs.ENSEMBL.mat) <- 1:length(gmcs.list.txt.unique)
  colnames(gMCSs.ENSEMBL.mat) <- genes.gMCSs.ENSEMBL
  
  pb = txtProgressBar(min = 0, max = length(gmcs.list.txt.unique), initial = 0, style = 3) 
  for (i in 1:length(gmcs.list.txt.unique)){
    setTxtProgressBar(pb, i)
    gmcs <- gMCSs.ENSEMBL.txt.list.num[[i]]
    gMCSs.ENSEMBL.mat[i,gmcs] <- 1
  }
  close(pb)
  
  gMCSs.ENSEMBL.mat <- Matrix(gMCSs.ENSEMBL.mat, sparse = T)  
  
  
  # remove names from lists
  names(gMCSs.ENSEMBL.txt) <- NULL
  names(gMCSs.ENSEMBL.txt.list) <- NULL
  names(gMCSs.ENSEMBL.txt.list.num) <- NULL
  
  # change formats
  table.gMCSs <- as.data.frame(apply(table.gMCSs,2,as.numeric))

  
  if (is.null(table.genes.HumanGEM)){
    return(list(gMCSs.ENSEMBL.mat = gMCSs.ENSEMBL.mat,
                table.gMCSs = table.gMCSs,
                genes.gMCSs.ENSEMBL = genes.gMCSs.ENSEMBL,
                gMCSs.ENSEMBL.txt = gMCSs.ENSEMBL.txt,
                # gMCSs.ENSEMBL.txt.list = gMCSs.ENSEMBL.txt.list,
                gMCSs.ENSEMBL.txt.list.num = gMCSs.ENSEMBL.txt.list.num,
                gMCSs.ENSEMBL = gMCSs.ENSEMBL.raw))
  } else {
    
    gMCSs.ENSEMBL.txt <- strsplit(gmcs.list.txt.unique, '--')
    gMCSs.SYMBOL.txt.list <- lapply(gMCSs.ENSEMBL.txt, function(x){table.genes.HumanGEM$SYMBOL[match(x, table.genes.HumanGEM$ENSEMBL)]})
    gMCSs.SYMBOL.txt <- lapply(gMCSs.SYMBOL.txt.list, paste, collapse = "--")
    
    # remove names from lists
    names(gMCSs.SYMBOL.txt.list) <- NULL
    names(gMCSs.SYMBOL.txt) <- NULL
    
    return(list(gMCSs.ENSEMBL.mat = gMCSs.ENSEMBL.mat,
                table.gMCSs = table.gMCSs,
                genes.gMCSs.ENSEMBL = genes.gMCSs.ENSEMBL,
                gMCSs.ENSEMBL.txt = gmcs.list.txt.unique, 
                gMCSs.SYMBOL.txt = gMCSs.SYMBOL.txt,
                table.genes.HumanGEM = table.genes.HumanGEM,
                # gMCSs.ENSEMBL.txt.list = gMCSs.ENSEMBL.txt.list,
                gMCSs.ENSEMBL.txt.list.num = gMCSs.ENSEMBL.txt.list.num,
                gMCSs.ENSEMBL = gMCSs.ENSEMBL.raw))
  }
  
  
}



